/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesApplicationModernisationRouteImport } from './routes/services.application-modernisation'
import { Route as ServicesCicdRouteImport } from './routes/services.cicd'
import { Route as ServicesCloudStrategyRouteImport } from './routes/services.cloud-strategy'
import { Route as ServicesCyberSecurityRouteImport } from './routes/services.cyber-security'
import { Route as ServicesDataAiRouteImport } from './routes/services.data-ai'
import { Route as ServicesDevopsAutomationRouteImport } from './routes/services.devops-automation'
import { Route as ServicesInfrastructureAsCodeRouteImport } from './routes/services.infrastructure-as-code'
import { Route as ServicesKubernetesPlatformEngineeringRouteImport } from './routes/services.kubernetes-platform-engineering'
import { Route as ServicesManagedServicesRouteImport } from './routes/services.managed-services'
import { Route as ServicesObservabilityManagedOpsRouteImport } from './routes/services.observability-managed-ops'
import { Route as ServicesPlatformEngineeringRouteImport } from './routes/services.platform-engineering'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesApplicationModernisationRoute =
  ServicesApplicationModernisationRouteImport.update({
    id: '/application-modernisation',
    path: '/application-modernisation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCicdRoute = ServicesCicdRouteImport.update({
  id: '/cicd',
  path: '/cicd',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCloudStrategyRoute = ServicesCloudStrategyRouteImport.update({
  id: '/cloud-strategy',
  path: '/cloud-strategy',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCyberSecurityRoute = ServicesCyberSecurityRouteImport.update({
  id: '/cyber-security',
  path: '/cyber-security',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDataAiRoute = ServicesDataAiRouteImport.update({
  id: '/data-ai',
  path: '/data-ai',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDevopsAutomationRoute =
  ServicesDevopsAutomationRouteImport.update({
    id: '/devops-automation',
    path: '/devops-automation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesInfrastructureAsCodeRoute =
  ServicesInfrastructureAsCodeRouteImport.update({
    id: '/infrastructure-as-code',
    path: '/infrastructure-as-code',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesKubernetesPlatformEngineeringRoute =
  ServicesKubernetesPlatformEngineeringRouteImport.update({
    id: '/kubernetes-platform-engineering',
    path: '/kubernetes-platform-engineering',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesManagedServicesRoute = ServicesManagedServicesRouteImport.update({
  id: '/managed-services',
  path: '/managed-services',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesObservabilityManagedOpsRoute =
  ServicesObservabilityManagedOpsRouteImport.update({
    id: '/observability-managed-ops',
    path: '/observability-managed-ops',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPlatformEngineeringRoute =
  ServicesPlatformEngineeringRouteImport.update({
    id: '/platform-engineering',
    path: '/platform-engineering',
    getParentRoute: () => ServicesRoute,
  } as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/services': typeof ServicesRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/services/application-modernisation': typeof ServicesApplicationModernisationRoute
  '/services/cicd': typeof ServicesCicdRoute
  '/services/cloud-strategy': typeof ServicesCloudStrategyRoute
  '/services/cyber-security': typeof ServicesCyberSecurityRoute
  '/services/data-ai': typeof ServicesDataAiRoute
  '/services/devops-automation': typeof ServicesDevopsAutomationRoute
  '/services/infrastructure-as-code': typeof ServicesInfrastructureAsCodeRoute
  '/services/kubernetes-platform-engineering': typeof ServicesKubernetesPlatformEngineeringRoute
  '/services/managed-services': typeof ServicesManagedServicesRoute
  '/services/observability-managed-ops': typeof ServicesObservabilityManagedOpsRoute
  '/services/platform-engineering': typeof ServicesPlatformEngineeringRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/services/application-modernisation': typeof ServicesApplicationModernisationRoute
  '/services/cicd': typeof ServicesCicdRoute
  '/services/cloud-strategy': typeof ServicesCloudStrategyRoute
  '/services/cyber-security': typeof ServicesCyberSecurityRoute
  '/services/data-ai': typeof ServicesDataAiRoute
  '/services/devops-automation': typeof ServicesDevopsAutomationRoute
  '/services/infrastructure-as-code': typeof ServicesInfrastructureAsCodeRoute
  '/services/kubernetes-platform-engineering': typeof ServicesKubernetesPlatformEngineeringRoute
  '/services/managed-services': typeof ServicesManagedServicesRoute
  '/services/observability-managed-ops': typeof ServicesObservabilityManagedOpsRoute
  '/services/platform-engineering': typeof ServicesPlatformEngineeringRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services': typeof ServicesIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/services': typeof ServicesRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/services/application-modernisation': typeof ServicesApplicationModernisationRoute
  '/services/cicd': typeof ServicesCicdRoute
  '/services/cloud-strategy': typeof ServicesCloudStrategyRoute
  '/services/cyber-security': typeof ServicesCyberSecurityRoute
  '/services/data-ai': typeof ServicesDataAiRoute
  '/services/devops-automation': typeof ServicesDevopsAutomationRoute
  '/services/infrastructure-as-code': typeof ServicesInfrastructureAsCodeRoute
  '/services/kubernetes-platform-engineering': typeof ServicesKubernetesPlatformEngineeringRoute
  '/services/managed-services': typeof ServicesManagedServicesRoute
  '/services/observability-managed-ops': typeof ServicesObservabilityManagedOpsRoute
  '/services/platform-engineering': typeof ServicesPlatformEngineeringRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/how-we-work'
    | '/services'
    | '/work'
    | '/services/application-modernisation'
    | '/services/cicd'
    | '/services/cloud-strategy'
    | '/services/cyber-security'
    | '/services/data-ai'
    | '/services/devops-automation'
    | '/services/infrastructure-as-code'
    | '/services/kubernetes-platform-engineering'
    | '/services/managed-services'
    | '/services/observability-managed-ops'
    | '/services/platform-engineering'
    | '/work/$slug'
    | '/services/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/how-we-work'
    | '/services/application-modernisation'
    | '/services/cicd'
    | '/services/cloud-strategy'
    | '/services/cyber-security'
    | '/services/data-ai'
    | '/services/devops-automation'
    | '/services/infrastructure-as-code'
    | '/services/kubernetes-platform-engineering'
    | '/services/managed-services'
    | '/services/observability-managed-ops'
    | '/services/platform-engineering'
    | '/work/$slug'
    | '/services'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/how-we-work'
    | '/services'
    | '/work'
    | '/services/application-modernisation'
    | '/services/cicd'
    | '/services/cloud-strategy'
    | '/services/cyber-security'
    | '/services/data-ai'
    | '/services/devops-automation'
    | '/services/infrastructure-as-code'
    | '/services/kubernetes-platform-engineering'
    | '/services/managed-services'
    | '/services/observability-managed-ops'
    | '/services/platform-engineering'
    | '/work/$slug'
    | '/services/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/application-modernisation': {
      id: '/services/application-modernisation'
      path: '/application-modernisation'
      fullPath: '/services/application-modernisation'
      preLoaderRoute: typeof ServicesApplicationModernisationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cicd': {
      id: '/services/cicd'
      path: '/cicd'
      fullPath: '/services/cicd'
      preLoaderRoute: typeof ServicesCicdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud-strategy': {
      id: '/services/cloud-strategy'
      path: '/cloud-strategy'
      fullPath: '/services/cloud-strategy'
      preLoaderRoute: typeof ServicesCloudStrategyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cyber-security': {
      id: '/services/cyber-security'
      path: '/cyber-security'
      fullPath: '/services/cyber-security'
      preLoaderRoute: typeof ServicesCyberSecurityRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/data-ai': {
      id: '/services/data-ai'
      path: '/data-ai'
      fullPath: '/services/data-ai'
      preLoaderRoute: typeof ServicesDataAiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/devops-automation': {
      id: '/services/devops-automation'
      path: '/devops-automation'
      fullPath: '/services/devops-automation'
      preLoaderRoute: typeof ServicesDevopsAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/infrastructure-as-code': {
      id: '/services/infrastructure-as-code'
      path: '/infrastructure-as-code'
      fullPath: '/services/infrastructure-as-code'
      preLoaderRoute: typeof ServicesInfrastructureAsCodeRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/kubernetes-platform-engineering': {
      id: '/services/kubernetes-platform-engineering'
      path: '/kubernetes-platform-engineering'
      fullPath: '/services/kubernetes-platform-engineering'
      preLoaderRoute: typeof ServicesKubernetesPlatformEngineeringRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/managed-services': {
      id: '/services/managed-services'
      path: '/managed-services'
      fullPath: '/services/managed-services'
      preLoaderRoute: typeof ServicesManagedServicesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/observability-managed-ops': {
      id: '/services/observability-managed-ops'
      path: '/observability-managed-ops'
      fullPath: '/services/observability-managed-ops'
      preLoaderRoute: typeof ServicesObservabilityManagedOpsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/platform-engineering': {
      id: '/services/platform-engineering'
      path: '/platform-engineering'
      fullPath: '/services/platform-engineering'
      preLoaderRoute: typeof ServicesPlatformEngineeringRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesApplicationModernisationRoute: typeof ServicesApplicationModernisationRoute
  ServicesCicdRoute: typeof ServicesCicdRoute
  ServicesCloudStrategyRoute: typeof ServicesCloudStrategyRoute
  ServicesCyberSecurityRoute: typeof ServicesCyberSecurityRoute
  ServicesDataAiRoute: typeof ServicesDataAiRoute
  ServicesDevopsAutomationRoute: typeof ServicesDevopsAutomationRoute
  ServicesInfrastructureAsCodeRoute: typeof ServicesInfrastructureAsCodeRoute
  ServicesKubernetesPlatformEngineeringRoute: typeof ServicesKubernetesPlatformEngineeringRoute
  ServicesManagedServicesRoute: typeof ServicesManagedServicesRoute
  ServicesObservabilityManagedOpsRoute: typeof ServicesObservabilityManagedOpsRoute
  ServicesPlatformEngineeringRoute: typeof ServicesPlatformEngineeringRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesApplicationModernisationRoute: ServicesApplicationModernisationRoute,
  ServicesCicdRoute: ServicesCicdRoute,
  ServicesCloudStrategyRoute: ServicesCloudStrategyRoute,
  ServicesCyberSecurityRoute: ServicesCyberSecurityRoute,
  ServicesDataAiRoute: ServicesDataAiRoute,
  ServicesDevopsAutomationRoute: ServicesDevopsAutomationRoute,
  ServicesInfrastructureAsCodeRoute: ServicesInfrastructureAsCodeRoute,
  ServicesKubernetesPlatformEngineeringRoute:
    ServicesKubernetesPlatformEngineeringRoute,
  ServicesManagedServicesRoute: ServicesManagedServicesRoute,
  ServicesObservabilityManagedOpsRoute: ServicesObservabilityManagedOpsRoute,
  ServicesPlatformEngineeringRoute: ServicesPlatformEngineeringRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  ServicesRoute: ServicesRouteWithChildren,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
